__tests__/PropTypesDevelopmentReact15.js, factoryWithTypeCheckers.js
We released `react@0.14.9` and `react-dom@0.14.9` that fix the false positive for this warning.
However I’m also limiting the number of times it gets printed so https://github.com/reactjs/react-redux/issues/669 is less annoying for people who haven’t updated yet.
=> Limit manual PropTypes call warning count

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, __tests__/PropTypesProductionReact15-test.js, factoryWithTypeCheckers.js
PropTypes type checking: Add additional check to UnionType checker to ensure only functions are used as argument of oneOfType.
This is especially handy to catch typos during PropType definition like for example:
```javascript
Greeting.propTypes = {
name: React.PropTypes.oneOfType([React.PropTypes.sting, React.PropTypes.func])
};
```
The pull request will print a warning 
`Invalid argument supplied to oneOfType, expected an array containing check functions.`
Pull Request taken over from React main Repository
https://github.com/facebook/react/pull/8823
=> improve union type checker error message

README.md
We took the API reference from the React Docs guide on 'Typechecking
with PropTypes' and added it to this README.
Once this lands we can remove it from those docs and link to these docs.
Why? So that we make it clear that this is a separate module that can be
used with other libraries as well, and not just a feature of React. Also
hopefully this will make things more clear.
We will also open a `good-first-bug` issue for someone to improve this
README and turn it into a more complete API reference, with examples
using PropTypes with other libraries.
Fixes https://github.com/facebook/react/issues/9467
=> Add API reference to README

package.json, yarn.lock
Fixes https://github.com/facebook/react/issues/9641
This tells browserify to remove `process.env.NODE_ENV` conditionals during bundling.
=> Add loose-envify browserify transform

factoryWithThrowingShims.js
When a library bundles a PROD build of `prop-types`, but it is used with a DEV version of React, we print a false positive error message:
>Failed prop type: React.PropTypes type checking code is stripped in production
This fixes it by checking the secret even in the production build.
Fixes https://github.com/reactjs/prop-types/issues/38.
=> Fix false positive when mixing DEV and PROD builds

README.md
Replaced 'comoponents' with 'components'
=> README: Fixed typo

__tests__/PropTypesDevelopmentReact15.js, factoryWithTypeCheckers.js
I adapted [`createStrictShapeTypeChecker`](https://github.com/facebook/react-native/blob/c3b25c9059f57ee8df5505628ff6221f11cf9234/Libraries/Utilities/createStrictShapeTypeChecker.js) from react native into a `PropTypes.exact` checker.
This operates exactly the same way as `PropTypes.shape` except it will warn on additional keys:
```js
check(PropTypes.shape({}), { foo: 1 }); // Okay.
check(PropTypes.exact({}), { foo: 1 }); // Warning!
```
This is a runtime version of [Flow's exact object types](https://flow.org/en/docs/types/objects/#toc-exact-object-types):
```js
type shape = { ... };
type exact = {| ... |};
```
=> Add exact type checker from react native

README.md
`js` is recognized by npmjs.com (`jsx` isn't) and there was no JSX here anyway.
=> 'jsx' code annotation changed to 'js'

checkPropTypes.js
Fixes an outdated error code string that points to `React.PropTypes` rather than the `prop-types` package. As discussed in https://github.com/facebook/react/pull/9842.
=> Update error message to point to prop-types package

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js
This warning was changed in https://github.com/facebook/prop-types/pull/71 and it didn't break any tests. This adds some simple test coverage for this warning.
=> Add test coverage for invalid validator warning

__tests__/PropTypesDevelopmentReact15.js, factoryWithThrowingShims.js, factoryWithTypeCheckers.js, package.json, yarn.lock
This addresses feedback provided in https://github.com/facebook/prop-types/pull/80 regarding https://github.com/facebook/prop-types/pull/41
* Production shim has been added for `exact` 
* `Object.assign` has been replaced with the `object-assign` polyfill
cc @gaearon
=> Re-add exact type checker

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, checkPropTypes.js
Closes https://github.com/facebook/react/issues/9068 that got already closed when prop-types was moved. There was another PR (https://github.com/facebook/react/pull/9140) for the same purpose that also got closed for the same reason.
CC @gaearon as he participated in https://github.com/facebook/react/pull/9140
Thanks.
=> Enhance warning message when a PropType is not correct

README.md
Ensure both unpkg and cdnjs are listed as CDNs, deprecate existing alias CDN reference in preference for best practice explicit version, and updated wording similar to React documentation.
This PR is recreated because I accidentally deleted original fork.
Reference: #99 
Updates:
* Ensured unpkg first
* Major.minor included for unpkg
=> Update README.md with improved importing for CDNs

CODE_OF_CONDUCT.md, CONTRIBUTING.md
**what is the change?:**
Even though this is a small project and we don't expect changes, it's
standard to include a `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` doc.
**why make this change?:**
Let's give folks info about how to contribute, to foster a welcoming open source community in the React ecosystem.
Exposing the COC via a separate markdown file is a standard being
promoted by Github via the Community Profile in order to meet their Open
Source Guide's recommended community standards.
As you can see, adding this file will improve the [prop-types Community Profile](https://github.com/facebook/prop-types/community)
checklist and increase the visibility of our COC.
**test plan:**
Viewing it on my branch -
**issue:**
internal task t23481323
=> Add `CONTRIBUTING` and `CODE_OF_CONDUCT`

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, yarn.lock
Failure seems to have been introduced with #68, before then tests are passing.
On that note, it would be great if CircleCI were set up for this repo. This cost me quite a bit of time today.
=> Fix failing tests

README.md
After an update to the docs, the production build was pointing to an outdated link. This commit directs the link to the appropriate location in the React docs.
=> Point readme to correct docs for production builds

checkPropTypes.js, factoryWithThrowingShims.js, factoryWithTypeCheckers.js, package.json, yarn.lock
See reasons in https://github.com/facebook/react/pull/13069.
This PR is complementary.
I chose to inline a simplified version of `warning` in two files where we use it, and replacing invariant calls with `new Error`. In case somebody relies on `Invariant Violation` being the name (e.g. in tests), I inlined `.name` assignments to match the `invariant` logic.
Without this PR, `fbjs` would stay a transitive dep of React.
=> Remove fbjs dependency

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, __tests__/PropTypesProductionReact15-test.js, __tests__/PropTypesProductionStandalone-test.js
It's better to define variables as consts and lets over vars.
=> Updated all vars in test files to consts and lets.

README.md
Let’s include `.exact` in the README! 🎉
Also shows that one can use `isRequired` on individual properties inside ´shape´ and ´exact´ and removes trailing spaces.
Thanks for maintaining this awesome project and a love letter 💌 to @gaearon! His documentation made me look up the typographic apostrophe ( ’ )!
=> Update README to include .exact()

.travis.yml, README.md, yarn.lock
In accordance with https://github.com/facebook/prop-types/issues/19#issuecomment-316482639,
includes config for TravisCI to run test reports on the master branch
and PR's to the master branch.
- Includes .travis.yml config file
- Includes current CI status badge in README
Closes #19.
Note: Travis was not building the yarn cache successfully until I rebuilt the lock file. `npm install` worked fine though.
The currently failing tests are fixed in https://github.com/facebook/prop-types/pull/129/files
=> Include CI for master branch and PR's

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, __tests__/PropTypesProductionReact15-test.js, checkPropTypes.js
Avoids the `Warning: Failed prop type: propValue.hasOwnProperty is not a function` warning when `hasOwnProperty` is not defined in the prototype chain.
See #183 for details.
---
- On the original issue @ljharb [noted something about `delete Object.prototype.hasOwnProperty` being a thing](https://github.com/facebook/prop-types/issues/183#issuecomment-390845818). I did not quite get this comment, so this solution might not work because of that. Just close this PR in that case.
- I did not add tests for the combined case of `PropTypes.shape({ q: PropTypes.objectOf(PropTypes.string) })` I pointed out in https://github.com/facebook/prop-types/issues/183#issuecomment-392545102, as I didn't know where to place them
=> Support validation when hasOwnProperty is not in prototype

README.md, __tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, __tests__/PropTypesProductionReact15-test.js, __tests__/PropTypesProductionStandalone-test.js, checkPropTypes.js, factoryWithThrowingShims.js, factoryWithTypeCheckers.js
When testing code using PropTypes, warnings fail unexpectedly due to caching behavior.  It would be useful for `resetWarningCache` to be part of the publicly exported API.
- Added test for current caching behavior of `PropTypes.checkPropTypes`
- Added test for new reset function `PropTypes.checkPropTypes.resetWarningCache`
- Implemented `PropTypes.checkPropTypes.resetWarningCache`
- Documented `PropTypes.checkPropTypes.resetWarningCache`
=> Export resetWarningCache

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, __tests__/PropTypesProductionReact15-test.js, factoryWithTypeCheckers.js
- Fixes error due to an attempt to coerce a Symbol to a string
- Improves formatting of the "expected" portion of the generated warning, outputting for example `["Symbol(A)","Symbol(B)"]` rather than `[null,null]`
Fixes #10
=> Fix oneOf when used with Symbols

package.json, yarn.lock
Following the discussion in #203, this PR move `loose-envify` from dependencies to devDependencies. 
I also took the opportunity to choose `loose-envify` over `envify` everywhere, as they are doing the same thing anyway. I have no opinion whether `loose-envify` is better than `envify` or not. Using `yarn run test` does not show any measurable difference in term of execution time, so I can switch back to `envify` if you prefer.
Closes #203.
=> Completely remove envify in favor of loose-envify

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, factoryWithTypeCheckers.js
Adds a different warning message for multiple arguments supplied to oneOf. A common mistake is to write `oneOf(x, y, z)` instead of `oneOf([x, y, z])` and this should help developers identifying the error.
=> Warn when multiple arguments were supplied to oneOf

README.md, __tests__/PropTypesDevelopmentStandalone-test.js, __tests__/PropTypesProductionStandalone-test.js, factoryWithThrowingShims.js, factoryWithTypeCheckers.js, index.js, package.json, yarn.lock
There is a missing prop type that is quite common for a lot of people: `PropTypes.component`. The `PropTypes.element` already exists to support `<MyComponent myProp={<MyOtherComponent />} />`. However, there is no way to easily type check: `<MyComponent myProp={MyOtherComponent} />`. Before React 16.3, we were getting away with `PropTypes.func`. 
However, with new features since React 16.3, there is a new challenge: forward ref! `forwardRef` is generating a React component, but in a different form: it is an object! This is breaking the old way of using the `PropTypes.func` and making the type checking unreliable. To fix this, we need a more complex prop type:
```
MyComponent.propTypes = {
myProp: PropTypes.oneOf([
PropTypes.func,
PropTypes.shape({
$$typeof: PropTypes.symbol
}) …
```
=> Add a PropTypes for React elementType (ie. MyComponent)

checkPropTypes.js
Just a text change, adds a stronger hint as to the most common issue.
This tries to prevent confusion as discussed in #33 
Sample:
```
> PropTypes.checkPropTypes({pname: PropTypes.stringzz}, {pname: false}, 'prop', 'MyCompo')
Warning: Failed prop type: MyCompo: type specification of prop `pname` is invalid; the type checker must be a function but is `undefined`. This often happens because of typos such as `React.PropTypes.function` instead of `React.PropTypes.func`.
```
Fixes #33.
=> Friendlier message when using a type checker that is not a function

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, factoryWithTypeCheckers.js
Fixes #220 
Possibly also #181 
This PR adds type checks for validators in `createShapeTypeChecker` and `createStrictShapeTypeChecker` so that they can fail loudly on invalid validators and everyone can be safe and happy! 😊
As outlined in #220 , providing any falsy value instead of a validator will cause validation to be skipped, meaning invalid props won't be caught. Providing a truthy value that's not a function results in a caught but displayed javascript error `Warning: Failed prop type: checker is not a function` which is better than nothing but not really that helpful.
The most likely cause of issues is typos in validator names, like `PropTypes.boolean` (which I've since discovered that I've written several times). As mentioned in #220 this is mitigated by using …
=> Fix silently failing invalid validators in shape

README.md
Add instructions for intentional inclusion of validation in production.
=> [Docs] Add instructions for intentional inclusion of validation in production

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, factoryWithTypeCheckers.js
Adds data object to returned error in type checker so that the expected types can be accessed from within oneOfType check. Also, updates the tests slightly.
Fixes #9. Fixes https://github.com/facebook/react/issues/1919.
=> Add expected types to oneOfType warning

checkPropTypes.js, factoryWithTypeCheckers.js, lib/has.js
According to DRY, extract `has` and `warning` message to lib as well as making the failing tests pass.
=> refactor: extract has and warning

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, __tests__/PropTypesProductionReact15-test.js
I just found this typo that effected three files in \_\_tests\_\_. I believe The first "Any type" test should be "should accept any value" and not "should should accept any value"
=> [Tests] Fixed typo: 'Any type *should* accept any value'

README.md
See https://github.com/facebook/prop-types/issues/334 for context and motivation.
=> Clarify usage of elementType (Closes #334)

package.json
This PR adds a package `sideEffects` field with a `false` value. This allows tree-shaking and dead-code-elimination to work much better, eliminating imports of `prop-types` if all of the imports end up being unused.
- esbuild docs: https://esbuild.github.io/api/#manual-tree-shaking-annotations
- webpack docs: https://webpack.js.org/guides/tree-shaking
This change could significantly improve the bundle size of projects that nest `propTypes` under a conditional so they will be eliminated from a production bundle, for example:
https://github.com/jaydenseric/device-agnostic-ui/blob/89e5ba0b8c0ee5a8fb38f4ed74e7f19a6b4970d7/src/public/components/Button.js#L25-L32
```js
if (typeof process === 'object' && process.env.NODE_ENV !== 'production') {
Button.displayName = 'Button';
Button.propTypes = { …
```
=> Add a package `sideEffects` field

.eslintignore, .eslintrc, factoryWithTypeCheckers.js
Hello,
I've  improved the documentation by adding additional ESLint rules and fixing some minor typos.
Additional ESLint rules: "no-multi-spaces": ["error"], "key-spacing": ["error"]
"no-multi-spaces" - Disallow multiple spaces;
"key-spacing" - Enforce consistent spacing between keys and values in object literal properties;
=> [eslint] enable some rules 

CHANGELOG.md, CONTRIBUTING.md, README.md
Fix branch name (master was renamed to main):
master -> main
=> Fix branch name

README.md, __tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, __tests__/PropTypesProductionReact15-test.js, __tests__/PropTypesProductionStandalone-test.js, factoryWithThrowingShims.js, factoryWithTypeCheckers.js
Closes #355.
Once tests pass, I'll merge this.
=> [New] add `PropTypes.bigint`

__tests__/PropTypesDevelopmentReact15.js, __tests__/PropTypesDevelopmentStandalone-test.js, __tests__/PropTypesProductionReact15-test.js, __tests__/PropTypesProductionStandalone-test.js, factoryWithTypeCheckers.js
=> [Fix] fix crash when a custom propType return lacks `.data`; call `hasOwnProperty` properly
